[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run start"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200